version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: kkijuk_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootPW
      MYSQL_DATABASE: kkijuk
      MYSQL_USER: test
      MYSQL_PASSWORD: testPW
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: kkijuk_redis_container
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
