CREATE DATABASE IF NOT EXISTS kkijuk;
CREATE DATABASE IF NOT EXISTS testDB;

CREATE USER IF NOT EXISTS 'test'@'%' IDENTIFIED BY 'testPW';

GRANT ALL PRIVILEGES ON kkijuk.* TO 'test'@'%';
GRANT ALL PRIVILEGES ON testDB.* TO 'test'@'%';

FLUSH PRIVILEGES;
