name: CI FOR MVP

on:
  push:
    branches:
      - mvp/apply
      - mvp/member
      - mvp/career
      - mvp/portfolio
      - feature/record
      - feature/home
      - feature/recruit-tag
      - feature/login
      - feature/login-memberTest
      - refactor/career
      - feature/login-recruit
      - fix/record
      - feature/errorFix
      - fix/credential
      - feature/dashboard

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'testDB'
          mysql user: 'test'
          mysql password: 'testPW'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
        
      - name: Build with Gradle Wrapper
        run: ./gradlew build
